[package]
name = "stb-perlin"
version = "0.1.0"
authors = ["Michael Carpenter"]
license = "MIT / Apache-2.0"
build = "build.rs"

[build-dependencies]
gcc = "0.3.8"
libc = "*"

[dependencies]
libc = "0.2.0"
